# Site settings
title: Striped
copyright_name: HTML5Up.
description: "A theme for Jekyll"
baseurl: ""
url: "http://localhost:4000"
twitter: twitter_name
github:  github_handle
facebook:  facebook_name
email:  you@domain.com
federated: https://gnusocial/user

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
#google_tracking_id: XX-XXXXXXXX-X

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /entry/:title
paginate: 5
exclude: ["README.md"]

gems: [jekyll-paginate, jekyll-feed]
